app:
  port: 8080
  host: localhost
  jwtSecret:
  release: false
  runMode: debug

db:
  mysql:
    address: langhai.xyz:3306
    user: root
    password: 2
    dbName: tiktok
    maxIdle: 20
    maxOpen: 20
    maxLifetime: 100
  redis:
    host: langhai.xyz:6379
    password: 0ziXrNTtZuWSDY7F
    maxIdle: 20
    maxActive: 20
    idleTimeOut: 100

log:
  logSavePath: logs
  logFileExt: log
  timeFormat: 2006-01-02 - 15:04:05.000
