app:
  port: 8080
  host: localhost
  jwtSecret:
  release: false
  runMode: debug

db:
  mysql:
    address: 127.0.0.1:3306
    user: TikTokAdmin
    password: melody
    dbName: tiktok
    maxIdle: 20
    maxOpen: 20
    maxLifetime: 100
  redis:
    host: 127.0.0.1:6379
    password:
    maxIdle: 20
    maxActive: 20
    idleTimeOut: 100

log:
  logSavePath: logs
  logFileExt: log
  timeFormat: 2006-01-02 - 15:04:05.000
