name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"

env:
  CI_BIN: tiktok-app

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: load Go 1.18 env
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        working-directory: cmd
        run: |
          GOOS=linux GPARCH=amd64 go build -o ${{ env.CI_BIN }}

      - name: Sync to oss
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-hangzhou.aliyuncs.com
          access-key-id: ${{ secrets.ALIYUN_KEY }}
          access-key-secret: ${{ secrets.ALIYUN_SECRET }}

      - name: cp files to aliyun
        run: |
          ossutil cp -rf cmd/${{ env.CI_BIN }} oss://sjc-mall/${{ env.CI_BIN }}/${{ env.CI_BIN }}

      - name: Webhook
        run: |
          curl ${{ secrets.WEBHOOK_URL }}