# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: deploy
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: load Go 1.18 env
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: checkout
        uses: actions/checkout@v3

      - name: executing remote ssh commands
      # 使用appleboy/ssh-action@master来执行命令
        uses: appleboy/ssh-action@v0.1.8
        with:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_USER }}
          KEY: ${{ secrets.DEPLOY_KEY }}
          SCRIPT: ${{ secrets.TARGET_PATH }} && git pull