name: Build
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: load Go 1.18 env
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        working-directory: cmd
        run: |
          GOOS=linux GPARCH=amd64 go build -o ${{ env.CI_BIN }}